name: base
channels:
  - nvidia/label/cuda-12.0.0
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - aiohttp=3.9.3
  - aiosignal=1.3.1
  - alembic=1.13.1
  - alsa-lib=1.2.12
  - altair=5.3.0
  - anyio=4.3.0
  - aom=3.8.2
  - appdirs=1.4.4
  - archspec=0.2.3
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - async_generator=1.10
  - attr=2.5.1
  - attrs=23.2.0
  - aws-c-auth=0.7.17
  - aws-c-cal=0.6.11
  - aws-c-common=0.9.15
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.7
  - aws-c-mqtt=0.10.3
  - aws-c-s3=0.5.7
  - aws-c-sdkutils=0.1.15
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.6
  - aws-sdk-cpp=1.11.267
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - binutils_impl_linux-64=2.40
  - blas=2.122
  - blas-devel=3.9.0
  - bleach=6.1.0
  - blinker=1.7.0
  - blosc=1.21.6
  - bokeh=3.4.1
  - boltons=24.0.0
  - bottleneck=1.3.6
  - branca=0.7.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brunsli=0.1
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.28.1
  - c-blosc2=2.14.4
  - ca-certificates=2024.8.30
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.0
  - certifi=2024.8.30
  - certipy=0.1.3
  - cffi=1.16.0
  - charls=2.4.2
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - comm=0.2.2
  - conda=24.3.0
  - conda-libmamba-solver=24.1.0
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - configurable-http-proxy=4.6.2
  - contourpy=1.2.1
  - cryptography=42.0.5
  - cuda-cccl=12.0.90
  - cuda-command-line-tools=12.0.0
  - cuda-compiler=12.0.0
  - cuda-cudart=12.0.107
  - cuda-cudart-dev=12.0.107
  - cuda-cudart-static=12.0.107
  - cuda-cuobjdump=12.0.76
  - cuda-cupti=12.0.90
  - cuda-cupti-static=12.0.90
  - cuda-cuxxfilt=12.0.76
  - cuda-documentation=12.0.76
  - cuda-driver-dev=12.0.107
  - cuda-gdb=12.0.90
  - cuda-libraries=12.0.0
  - cuda-libraries-dev=12.0.0
  - cuda-libraries-static=12.0.0
  - cuda-nsight=12.0.78
  - cuda-nsight-compute=12.0.0
  - cuda-nvcc=12.0.76
  - cuda-nvdisasm=12.0.76
  - cuda-nvml-dev=12.0.76
  - cuda-nvprof=12.0.90
  - cuda-nvprune=12.0.76
  - cuda-nvrtc=12.0.76
  - cuda-nvrtc-dev=12.0.76
  - cuda-nvrtc-static=12.0.76
  - cuda-nvtx=12.0.76
  - cuda-nvvp=12.0.90
  - cuda-opencl=12.0.76
  - cuda-opencl-dev=12.0.76
  - cuda-profiler-api=12.0.76
  - cuda-sanitizer-api=12.0.90
  - cuda-toolkit=12.0.0
  - cuda-tools=12.0.0
  - cuda-version=12.0
  - cuda-visual-tools=12.0.0
  - curl=8.10.0
  - cycler=0.12.1
  - cython=3.0.10
  - cytoolz=0.12.3
  - dask=2024.4.1
  - dask-core=2024.4.1
  - dask-expr=1.0.11
  - datascience=0.17.6
  - dav1d=1.2.1
  - dbus=1.13.6
  - debugpy=1.8.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.8
  - distributed=2024.4.1
  - distro=1.9.0
  - dpkt=1.9.8
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.6.2
  - fmt=10.2.1
  - folium=0.17.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.51.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.4.1
  - fsspec=2024.3.1
  - gcc_impl_linux-64=13.2.0
  - gds-tools=1.5.0.59
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gflags=2.2.2
  - gfortran_impl_linux-64=13.2.0
  - giflib=5.2.2
  - gitdb=4.0.11
  - gitpython=3.1.43
  - glib=2.80.3
  - glib-tools=2.80.3
  - glog=0.7.0
  - gmp=6.3.0
  - gmpy2=2.1.2
  - gputil=1.4.0
  - graphite2=1.3.13
  - greenlet=3.0.3
  - gsl=2.7
  - gst-plugins-base=1.24.7
  - gstreamer=1.24.7
  - gxx_impl_linux-64=13.2.0
  - h11=0.14.0
  - h2=4.1.0
  - h5py=3.11.0
  - harfbuzz=9.0.0
  - hdf5=1.14.3
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.27.0
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.7
  - imagecodecs=2024.6.1
  - imageio=2.34.0
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - importlib_resources=6.4.0
  - iniconfig=2.0.0
  - ipykernel=6.29.3
  - ipympl=0.9.4
  - ipython=8.22.2
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.2
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.3
  - joblib=1.4.0
  - json5=0.9.25
  - jsonpatch=1.33
  - jsonpointer=2.4
  - jsonschema=4.21.1
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.21.1
  - jupyter-lsp=2.2.5
  - jupyter-pluto-proxy=0.1.2
  - jupyter-server-mathjax=0.2.6
  - jupyter-server-proxy=4.1.2
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.2
  - jupyter_server_terminals=0.5.3
  - jupyter_telemetry=0.1.0
  - jupyterhub=4.1.5
  - jupyterhub-base=4.1.5
  - jupyterlab=4.2.4
  - jupyterlab-fasta=3.3.0
  - jupyterlab-geojson=3.4.0
  - jupyterlab-git=0.50.0
  - jupyterlab-latex=4.1.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_rise=0.42.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.10
  - jxrlib=1.1
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - lame=3.100
  - lazy_loader=0.4
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.1
  - libaec=1.1.3
  - libarchive=3.7.4
  - libarrow=15.0.2
  - libarrow-acero=15.0.2
  - libarrow-dataset=15.0.2
  - libarrow-flight=15.0.2
  - libarrow-flight-sql=15.0.2
  - libarrow-gandiva=15.0.2
  - libarrow-substrait=15.0.2
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libavif16=1.0.4
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.69
  - libcblas=3.9.0
  - libclang-cpp15=15.0.7
  - libclang13=18.1.8
  - libcrc32c=1.1.2
  - libcublas=12.0.1.189
  - libcublas-dev=12.0.1.189
  - libcublas-static=12.0.1.189
  - libcufft=11.0.0.21
  - libcufft-dev=11.0.0.21
  - libcufft-static=11.0.0.21
  - libcufile=1.5.0.59
  - libcufile-dev=1.5.0.59
  - libcufile-static=1.5.0.59
  - libcups=2.3.3
  - libcurand=10.3.1.50
  - libcurand-dev=10.3.1.50
  - libcurand-static=10.3.1.50
  - libcurl=8.10.0
  - libcusolver=11.4.2.57
  - libcusolver-dev=11.4.2.57
  - libcusolver-static=11.4.2.57
  - libcusparse=12.0.0.76
  - libcusparse-dev=12.0.0.76
  - libcusparse-static=12.0.0.76
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc=14.1.0
  - libgcc-devel_linux-64=13.2.0
  - libgcc-ng=14.1.0
  - libgcrypt=1.11.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgit2=1.8.1
  - libglib=2.80.3
  - libgomp=14.1.0
  - libgoogle-cloud=2.22.0
  - libgoogle-cloud-storage=2.22.0
  - libgpg-error=1.50
  - libgrpc=1.62.2
  - libhwloc=2.10.0
  - libhwy=1.1.0
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - libjxl=0.10.1
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm14=14.0.6
  - libllvm15=15.0.7
  - libllvm16=16.0.6
  - libllvm18=18.1.8
  - libmamba=1.5.8
  - libmambapy=1.5.8
  - libnghttp2=1.58.0
  - libnl=3.9.0
  - libnpp=12.0.0.30
  - libnpp-dev=12.0.0.30
  - libnpp-static=12.0.0.30
  - libnsl=2.0.1
  - libnvjitlink=12.0.76
  - libnvjitlink-dev=12.0.76
  - libnvjpeg=12.0.0.28
  - libnvjpeg-dev=12.0.0.28
  - libnvjpeg-static=12.0.0.28
  - libnvvm-samples=12.0.94
  - libogg=1.3.5
  - libopenblas=0.3.27
  - libopus=1.3.1
  - libparquet=15.0.2
  - libpng=1.6.44
  - libpq=16.4
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsanitizer=13.2.0
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsolv=0.7.30
  - libsqlite=3.46.1
  - libssh2=1.11.0
  - libstdcxx=14.1.0
  - libstdcxx-devel_linux-64=13.2.0
  - libstdcxx-ng=13.2.0
  - libsystemd0=256.6
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libuv=1.48.0
  - libvorbis=1.3.7
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.12.7
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - llvm-openmp=18.1.8
  - llvmlite=0.43.0
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.9.4
  - lzo=2.10
  - make=4.3
  - mako=1.3.3
  - mamba=1.5.8
  - markupsafe=2.1.5
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.7
  - menuinst=2.0.2
  - mistune=3.0.2
  - mock=5.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.6
  - mpmath=1.3.0
  - msgpack-python=1.0.7
  - multidict=6.0.5
  - munkres=1.1.4
  - mysql-common=8.3.0
  - mysql-libs=8.3.0
  - nbclassic=1.1.0
  - nbclient=0.10.0
  - nbconvert=7.16.4
  - nbconvert-core=7.16.4
  - nbconvert-pandoc=7.16.4
  - nbdime=4.0.1
  - nbformat=5.10.4
  - nbgrader=0.9.3
  - nccl=2.22.3.1
  - ncurses=6.4.20240210
  - nest-asyncio=1.6.0
  - networkx=3.3
  - nltk=3.9.1
  - nodejs=22.6.0
  - nomkl=1.0
  - nose=1.3.7
  - notebook=7.2.1
  - notebook-shim=0.2.4
  - nsight-compute=2022.4.0.15
  - nspr=4.35
  - nss=3.104
  - numba=0.60.0
  - numexpr=2.9.0
  - numpy=1.26.4
  - oauthlib=3.2.2
  - openblas=0.3.27
  - openjpeg=2.5.2
  - openpyxl=3.1.2
  - openssl=3.3.2
  - orc=2.0.0
  - overrides=7.7.0
  - packaging=24.0
  - pamela=1.1.0
  - pandas=2.2.2
  - pandoc=3.1.13
  - pandocfilters=1.5.0
  - pango=1.54.0
  - parso=0.8.4
  - partd=1.4.1
  - patsy=0.5.6
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.0
  - pixman=0.43.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.0
  - plotly=5.24.1
  - pluggy=1.5.0
  - ply=3.11
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio-client=17.0
  - pure_eval=0.2.2
  - py-cpuinfo=9.0.0
  - pyarrow=15.0.2
  - pyarrow-hotfix=0.6
  - pybind11-abi=4
  - pycocotools=2.0.8
  - pycosat=0.6.6
  - pycparser=2.22
  - pycurl=7.45.3
  - pygments=2.17.2
  - pyjwt=2.8.0
  - pynndescent=0.5.13
  - pyopenssl=24.0.0
  - pyparsing=3.1.2
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - pytables=3.9.2
  - pytest=8.3.3
  - python=3.11.9
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.19.1
  - python-json-logger=2.0.7
  - python-tzdata=2024.1
  - python_abi=3.11
  - pytz=2024.1
  - pywavelets=1.4.1
  - pyyaml=6.0.1
  - pyzmq=26.0.0
  - qt-main=5.15.8
  - r-askpass=1.2.0
  - r-assertthat=0.2.1
  - r-backports=1.4.1
  - r-base=4.3.3
  - r-base64enc=0.1_3
  - r-bit=4.0.5
  - r-bit64=4.0.5
  - r-bitops=1.0_7
  - r-blob=1.2.4
  - r-brew=1.0_10
  - r-brio=1.1.4
  - r-broom=1.0.5
  - r-bslib=0.7.0
  - r-cachem=1.0.8
  - r-callr=3.7.6
  - r-caret=6.0_94
  - r-cellranger=1.1.0
  - r-class=7.3_22
  - r-cli=3.6.2
  - r-clipr=0.8.0
  - r-clock=0.7.0
  - r-codetools=0.2_20
  - r-colorspace=2.1_0
  - r-commonmark=1.9.1
  - r-conflicted=1.2.0
  - r-covr=3.6.4
  - r-cpp11=0.4.7
  - r-crayon=1.5.2
  - r-credentials=2.0.1
  - r-crosstalk=1.2.1
  - r-curl=5.1.0
  - r-data.table=1.15.4
  - r-dbi=1.2.2
  - r-dbplyr=2.4.0
  - r-desc=1.4.3
  - r-devtools=2.4.5
  - r-diagram=1.6.5
  - r-dials=1.2.1
  - r-dicedesign=1.10
  - r-diffobj=0.3.5
  - r-digest=0.6.35
  - r-dofuture=1.0.1
  - r-downlit=0.4.3
  - r-dplyr=1.1.4
  - r-dt=0.33
  - r-dtplyr=1.3.1
  - r-e1071=1.7_14
  - r-ellipsis=0.3.2
  - r-evaluate=0.23
  - r-fansi=1.0.6
  - r-farver=2.1.1
  - r-fastmap=1.1.1
  - r-fontawesome=0.5.2
  - r-forcats=1.0.0
  - r-foreach=1.5.2
  - r-forecast=8.22.0
  - r-fracdiff=1.5_3
  - r-fs=1.6.3
  - r-furrr=0.3.1
  - r-future=1.33.2
  - r-future.apply=1.11.2
  - r-gargle=1.5.2
  - r-generics=0.1.3
  - r-gert=2.1.1
  - r-ggplot2=3.5.0
  - r-gh=1.4.1
  - r-git2r=0.33.0
  - r-gitcreds=0.1.2
  - r-globals=0.16.3
  - r-glue=1.7.0
  - r-googledrive=2.1.1
  - r-googlesheets4=1.1.1
  - r-gower=1.0.1
  - r-gpfit=1.0_8
  - r-gtable=0.3.4
  - r-hardhat=1.3.1
  - r-haven=2.5.4
  - r-hexbin=1.28.3
  - r-highr=0.10
  - r-hms=1.1.3
  - r-htmltools=0.5.8.1
  - r-htmlwidgets=1.6.4
  - r-httpuv=1.6.15
  - r-httr=1.4.7
  - r-httr2=1.0.1
  - r-ids=1.0.1
  - r-infer=1.0.7
  - r-ini=0.3.1
  - r-ipred=0.9_14
  - r-irdisplay=1.1
  - r-irkernel=1.3.2
  - r-isoband=0.2.7
  - r-iterators=1.0.14
  - r-jquerylib=0.1.4
  - r-jsonlite=1.8.8
  - r-kernsmooth=2.23_22
  - r-knitr=1.46
  - r-labeling=0.4.3
  - r-later=1.3.2
  - r-lattice=0.22_6
  - r-lava=1.7.3
  - r-lazyeval=0.2.2
  - r-lhs=1.1.6
  - r-lifecycle=1.0.4
  - r-listenv=0.9.1
  - r-lmtest=0.9_40
  - r-lubridate=1.9.3
  - r-magrittr=2.0.3
  - r-markdown=1.13
  - r-mass=7.3_60
  - r-matrix=1.6_5
  - r-memoise=2.0.1
  - r-mgcv=1.9_1
  - r-mime=0.12
  - r-miniui=0.1.1.1
  - r-modeldata=1.3.0
  - r-modelenv=0.1.1
  - r-modelmetrics=1.2.2.2
  - r-modelr=0.1.11
  - r-munsell=0.5.1
  - r-nlme=3.1_164
  - r-nnet=7.3_19
  - r-numderiv=2016.8_1.1
  - r-nycflights13=1.0.2
  - r-openssl=2.1.1
  - r-parallelly=1.37.1
  - r-parsnip=1.2.1
  - r-patchwork=1.2.0
  - r-pbdzmq=0.3_11
  - r-pillar=1.9.0
  - r-pkgbuild=1.4.4
  - r-pkgconfig=2.0.3
  - r-pkgdown=2.0.9
  - r-pkgload=1.3.4
  - r-plogr=0.2.0
  - r-plyr=1.8.9
  - r-praise=1.0.0
  - r-prettyunits=1.2.0
  - r-proc=1.18.5
  - r-processx=3.8.4
  - r-prodlim=2023.08.28
  - r-profvis=0.3.8
  - r-progress=1.2.3
  - r-progressr=0.14.0
  - r-promises=1.3.0
  - r-proxy=0.4_27
  - r-ps=1.7.6
  - r-purrr=1.0.2
  - r-quadprog=1.5_8
  - r-quantmod=0.4.26
  - r-r6=2.5.1
  - r-ragg=1.3.0
  - r-randomforest=4.7_1.1
  - r-rappdirs=0.3.3
  - r-rcmdcheck=1.4.0
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.0.12
  - r-rcpparmadillo=0.12.8.2.1
  - r-rcurl=1.98_1.14
  - r-readr=2.1.5
  - r-readxl=1.4.3
  - r-recipes=1.0.10
  - r-rematch=2.0.0
  - r-rematch2=2.1.2
  - r-remotes=2.5.0
  - r-repr=1.1.7
  - r-reprex=2.1.0
  - r-reshape2=1.4.4
  - r-rex=1.2.1
  - r-rlang=1.1.3
  - r-rmarkdown=2.26
  - r-rodbc=1.3_23
  - r-roxygen2=7.3.1
  - r-rpart=4.1.23
  - r-rprojroot=2.0.4
  - r-rsample=1.2.1
  - r-rsqlite=2.3.4
  - r-rstudioapi=0.16.0
  - r-rversions=2.1.2
  - r-rvest=1.0.4
  - r-sass=0.4.9
  - r-scales=1.3.0
  - r-selectr=0.4_2
  - r-sessioninfo=1.2.2
  - r-shape=1.4.6.1
  - r-shiny=1.8.1.1
  - r-slider=0.3.1
  - r-sourcetools=0.1.7_1
  - r-squarem=2021.1
  - r-stringi=1.8.4
  - r-stringr=1.5.1
  - r-survival=3.5_8
  - r-sys=3.4.2
  - r-systemfonts=1.0.5
  - r-testthat=3.2.1.1
  - r-textshaping=0.4.0
  - r-tibble=3.2.1
  - r-tidymodels=1.2.0
  - r-tidyr=1.3.1
  - r-tidyselect=1.2.0
  - r-tidyverse=2.0.0
  - r-timechange=0.3.0
  - r-timedate=4032.109
  - r-tinytex=0.50
  - r-tseries=0.10_55
  - r-ttr=0.24.4
  - r-tune=1.2.1
  - r-tzdb=0.4.0
  - r-urca=1.3_3
  - r-urlchecker=1.0.1
  - r-usethis=2.2.3
  - r-utf8=1.2.4
  - r-uuid=1.2_0
  - r-vctrs=0.6.5
  - r-viridislite=0.4.2
  - r-vroom=1.6.5
  - r-waldo=0.5.2
  - r-warp=0.2.1
  - r-whisker=0.4.1
  - r-withr=3.0.0
  - r-workflows=1.1.4
  - r-workflowsets=1.1.0
  - r-xfun=0.43
  - r-xml2=1.3.6
  - r-xopen=1.0.0
  - r-xtable=1.8_4
  - r-xts=0.13.2
  - r-yaml=2.3.8
  - r-yardstick=1.3.1
  - r-zip=2.3.1
  - r-zoo=1.8_12
  - rapidfuzz=3.9.7
  - rav1e=0.6.6
  - rdma-core=51.0
  - re2=2023.09.01
  - readline=8.2
  - referencing=0.34.0
  - regex=2024.9.11
  - reproc=14.2.4.post0
  - reproc-cpp=14.2.4.post0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.18.0
  - rpy2=3.5.11
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - s2n=1.4.12
  - scapy=2.5.0
  - scikit-image=0.22.0
  - scikit-learn=1.4.2
  - scipy=1.13.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - sed=4.8
  - send2trash=1.8.3
  - setuptools=69.5.1
  - simpervisor=1.0.0
  - simplegeneric=0.8.1
  - sip=6.7.12
  - six=1.16.0
  - smmap=5.0.0
  - snappy=1.2.0
  - sniffio=1.3.1
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sqlalchemy=2.0.29
  - stack_data=0.6.2
  - statsmodels=0.14.2
  - svt-av1=2.0.0
  - sympy=1.12
  - sysroot_linux-64=2.12
  - tbb=2021.12.0
  - tblib=3.0.0
  - tenacity=9.0.0
  - terminado=0.18.1
  - threadpoolctl=3.4.0
  - tifffile=2024.4.18
  - tinycss2=1.2.1
  - tk=8.6.13
  - tktable=2.10
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.1
  - tornado=6.4
  - traitlets=5.14.2
  - truststore=0.8.0
  - types-python-dateutil=2.9.0.20240316
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - typing_utils=0.1.0
  - tzdata=2024a
  - tzlocal=5.2
  - ucx=1.15.0
  - umap-learn=0.5.6
  - unixodbc=2.3.12
  - uri-template=1.3.0
  - urllib3=2.2.1
  - wcwidth=0.2.13
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.7.0
  - wheel=0.43.0
  - widgetsnbextension=4.0.10
  - xcb-util=0.4.1
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.42
  - xlrd=2.0.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-libxt=1.3.0
  - xorg-libxxf86vm=1.1.5
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xyzservices=2024.4.0
  - xz=5.2.6
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - yarl=1.9.4
  - zeromq=4.3.5
  - zfp=1.0.1
  - zict=3.0.0
  - zipp=3.17.0
  - zlib=1.3.1
  - zlib-ng=2.0.7
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - -r requirements.txt
      - absl-py==2.1.0
      - accelerate==0.34.2
      - array-record==0.5.1
      - astunparse==1.6.3
      - cachetools==5.5.0
      - datasets==3.0.0
      - dm-tree==0.1.8
      - docstring-parser==0.16
      - env-backup==0.0.3
      - etils==1.9.4
      - filelock==3.13.1
      - flatbuffers==24.3.25
      - gast==0.6.0
      - google-auth==2.34.0
      - google-auth-oauthlib==1.2.1
      - google-pasta==0.2.0
      - googleapis-common-protos==1.65.0
      - grpcio==1.66.1
      - huggingface-hub==0.25.0
      - immutabledict==4.2.0
      - jupyter-resource-usage==1.1.0
      - keras==2.15.0
      - libclang==18.1.1
      - markdown==3.7
      - ml-dtypes==0.2.0
      - multiprocess==0.70.16
      - nbgitpuller==1.2.2.dev0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.1.105
      - nvidia-nvtx-cu12==12.1.105
      - opencv-contrib-python-headless==4.10.0.84
      - opencv-python==4.10.0.84
      - opt-einsum==3.3.0
      - promise==2.3
      - protobuf==4.25.4
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - safetensors==0.4.5
      - simple-parsing==0.1.6
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.0
      - tensorflow-datasets==4.9.6
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-metadata==1.15.0
      - tensorrt==8.6.1
      - tensorrt-bindings==8.6.1
      - tensorrt-libs==8.6.1
      - termcolor==2.4.0
      - timeout-decorator==0.5.0
      - timm==1.0.9
      - tokenizers==0.19.1
      - torch==2.2.1+cu121
      - torchaudio==2.2.1+cu121
      - torchvision==0.17.1+cu121
      - tqdm==4.66.5
      - transformers==4.44.2
      - triton==2.2.0
      - werkzeug==3.0.4
      - wrapt==1.14.1
      - xxhash==3.5.0
