remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

# Enable MathJax for Equations
kramdown:
  math_engine: mathjax
  syntax_highlighter_opts:
    block:
      math_engine: mathjax
    span:
      math_engine: mathjax
